---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Update apt repository cache
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Install firewalld dependencies
      ansible.builtin.package:
        name: netbase
      when: ansible_os_family == "Debian"
    
    - name: Install firewalld
      ansible.builtin.package:
        name: firewalld
        state: present

    - name: Enable firewalld
      ansible.builtin.systemd:
        name: firewalld
        enabled: true
        state: started

    - name: Install ssh client
      ansible.builtin.package:
        name: "{{ 'openssh-clients' if (ansible_os_family == 'RedHat')  else 'openssh-client' }}"
        state: present

    - name: Ensure /etc/ssh exists
      ansible.builtin.file:
        path: /etc/ssh
        state: directory
        mode: '0755'

    - name: Ensure /var/run/sshd exists
      ansible.builtin.file:
        path: /var/run/sshd
        state: directory
        mode: '0755'
      when: ansible_os_family == 'Debian'

    - name: Recreate host keys - create new keys 1/3
      ansible.builtin.command: ssh-keygen -t rsa -b 4096 -N '' -f /etc/ssh/ssh_host_rsa_key
      changed_when: true

    - name: Recreate host keys - create new keys 2/3
      ansible.builtin.command: ssh-keygen -t ecdsa -N '' -f /etc/ssh/ssh_host_ecdsa_key
      changed_when: true

    - name: Recreate host keys - create new keys 1/3
      ansible.builtin.command: ssh-keygen -t ed25519 -N '' -f /etc/ssh/ssh_host_ed25519_key
      changed_when: true
