---
- name: Configure ssh port in firewalld service
  ansible.builtin.template:
    src: ssh.xml.j2
    dest: /etc/firewalld/services/ssh.xml
    owner: root
    group: root
    mode: '0644'
  notify: reload-firewall

- name: Permit ssh traffic in default zone
  ansible.posix.firewalld:
    service: ssh
    permanent: true
    immediate: true
    zone: "{{ ssh_firewalld_zone | default(omit, true) }}"
    state: enabled
