---
# tasks file for ssh
#
- name: Set platform/version specific variables
  ansible.builtin.include_tasks: setup_vars.yml

- name: OS is supported
  ansible.builtin.meta: end_host
  when:
    - not __ssh_os_supported | bool

- name: Manage sshd if enabled
  ansible.builtin.include_tasks: sshd.yml
  when: ssh_manage_sshd | bool

- name: Manage ssh client
  ansible.builtin.include_tasks: ssh.yml

- name: Manage MOTD
  ansible.builtin.include_tasks: motd.yml
  when: ssh_manage_motd_file | bool

- name: Manage firewalld
  ansible.builtin.include_tasks: firewall.yml
  when: ssh_manage_firewall | bool
