---
# The file names differe in RHEL-8 and RHEL-9
- name: Remove default Red Hat ssh client config file
  ansible.builtin.file:
    name: "{{ item }}"
    state: absent
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version | int >= 8
  loop:
    - /etc/ssh/ssh_config.d/05-redhat.conf
    - /etc/ssh/ssh_config.d/50-redhat.conf

- name: Copy known hosts files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/ssh/{{ item | basename }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ ssh_global_known_hosts }}"
  when: ssh_global_known_hosts | length > 0

- name: Manage ssh client config
  ansible.builtin.template:
    src: ssh_config.j2
    dest: /etc/ssh/ssh_config
    owner: root
    group: root
    mode: '0644'
