---
- name: Ensure sshd is installed
  ansible.builtin.package:
    name: '{{ __ssh_server_packages }}'
    state: present

- name: Remove default sshd config file on newer EL9
  ansible.builtin.file:
    name: "/etc/ssh/sshd_config.d/50-redhat.conf"
    state: absent
  notify: restart-sshd
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version | int >= 9

- name: Manage sshd config
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0640'
    validate: /usr/sbin/sshd -t -f %s
  notify: restart-sshd

- name: Start ssh service
  ansible.builtin.systemd:
    name: sshd
    state: started
    enabled: true
    daemon_reload: true

- name: Manage firewalld
  when: ssh_manage_firewall | bool
  block:
    - name: Configure ssh port in firewalld service
      ansible.builtin.template:
        src: ssh.xml.j2
        dest: /etc/firewalld/services/ssh.xml
        owner: root
        group: root
        mode: '0644'
      notify: reload-firewalld

    - name: Permit ssh traffic in default zone
      ansible.posix.firewalld:
        service: ssh
        permanent: true
        immediate: true
        state: enabled

- name: Install motd banner
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: '0644'
