---
- name: Ensure sshd is installed
  ansible.builtin.package:
    name: '{{ __ssh_server_packages }}'
    state: present

- name: Remove default sshd config file on newer EL9
  ansible.builtin.file:
    name: "/etc/ssh/sshd_config.d/50-redhat.conf"
    state: absent
  notify: restart-sshd
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version | int >= 9

- name: Disable system-wide crypto policy usage on RHEL-8
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/sshd
    regexp: '^#.*CRYPTO_POLICY='
    line: 'CRYPTO_POLICY='
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version | int == 8

- name: Purge short primes
  block:
    - name: Identify primes shorter than 3071 bits in moduli file
      ansible.builtin.shell: "awk '$5 < 3071' /etc/ssh/moduli"
      changed_when: false
      register: short_moduli

    - name: Remove short primes from moduli file
      ansible.builtin.shell: |
        awk '$5 >= 3071' /etc/ssh/moduli > /etc/ssh/moduli.tmp
        mv /etc/ssh/moduli.tmp /etc/ssh/moduli
      changed_when: true
      when: short_moduli.stdout != ""
      notify: restart-sshd

- name: Manage sshd config
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0640'
    validate: /usr/sbin/sshd -t -f %s
  notify: restart-sshd

- name: Start ssh service
  ansible.builtin.systemd:
    name: sshd
    state: started
    enabled: true
    daemon_reload: true
