---
# handlers file for ssh
#
- name: Reload firewalld service
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded
  listen: reload-firewall

- name: Restart sshd service
  ansible.builtin.systemd:
    name: sshd
    state: restarted
  listen: restart-sshd
