---
# handlers file for ssh
#
- name: Reload firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded

- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
